language: node_js
node_js:
- 'node'
before_install:
- rvm install 2.2.2
before_script:
- gem install awesome_bot
script:
- npm run test
- awesome_bot README.md --white-list apple.com/fonts,medium.engineering,awesome.re